import type { Catalog } from "./types";

// Placeholder structure. Populate items with 20–30 curated entries per category.
export const catalog: Catalog = {
  items: [
    {
      id: "nav-tubelight-01",
      title: "Tubelight Navigation Bar",
      category: "Navigation Menu",
      provider: "custom",
      previewComponent: "TubelightNavbarDemo",
      sourceUrl: "#",
      tags: ["animated", "responsive", "modern", "tubelight"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "nav-dropdown-menu-01",
      title: "Navigation Menu with Dropdown",
      category: "Navigation Menu",
      provider: "custom",
      previewComponent: "HeaderDemo",
      sourceUrl: "#",
      tags: ["dropdown", "responsive", "modern", "sticky"],
      license: "MIT",
      version: "1.0.0",
      badges: ["accessible"],
    },
    {
      id: "nav-hover-menu-01",
      title: "Hover Menu Navigation",
      category: "Navigation Menu",
      provider: "custom",
      previewComponent: "NavbarMenuDemo",
      sourceUrl: "#",
      tags: ["animated", "hover", "modern", "responsive"],
      license: "MIT",
      version: "1.0.0",
      badges: ["popular"],
    },
    {
      id: "nav-grid-menu-01",
      title: "Grid Navigation Menu",
      category: "Navigation Menu",
      provider: "custom",
      previewComponent: "NavigationMenuGridDemo",
      sourceUrl: "#",
      tags: ["grid", "modern", "responsive", "mobile"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "nav-animated-cursor-01",
      title: "Animated Cursor Navigation",
      category: "Navigation Menu",
      provider: "custom",
      previewComponent: "NavHeaderDemo",
      sourceUrl: "#",
      tags: ["animated", "cursor", "modern", "interactive"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "nav-staggered-menu-01",
      title: "Staggered Menu Navigation",
      category: "Navigation Menu",
      provider: "custom",
      previewComponent: "StaggeredMenuDemo",
      sourceUrl: "#",
      tags: ["animated", "staggered", "gsap", "modern"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "nav-card-nav-01",
      title: "Card Navigation Menu",
      category: "Navigation Menu",
      provider: "custom",
      previewComponent: "CardNavDemo",
      sourceUrl: "#",
      tags: ["animated", "cards", "gsap", "modern"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "hero-animated-01",
      title: "Animated Hero Section",
      category: "Hero",
      provider: "custom",
      previewComponent: "HeroDemo",
      sourceUrl: "#",
      tags: ["animated", "framer-motion", "modern", "responsive"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "hero-neural-network-01",
      title: "Neural Network Hero",
      category: "Hero",
      provider: "custom",
      previewComponent: "NeuralNetworkHeroDemo",
      sourceUrl: "#",
      tags: ["animated", "threejs", "shader", "gsap", "modern"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "hero-shader-showcase-01",
      title: "Shader Showcase Hero",
      category: "Hero",
      provider: "custom",
      previewComponent: "ShaderShowcaseDemo",
      sourceUrl: "#",
      tags: ["animated", "shader", "mesh-gradient", "framer-motion", "modern"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "hero-interactive-accordion-01",
      title: "Interactive Image Accordion Hero",
      category: "Hero",
      provider: "custom",
      previewComponent: "InteractiveImageAccordionDemo",
      sourceUrl: "#",
      tags: ["animated", "accordion", "interactive", "images", "modern"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "hero-video-01",
      title: "Split Screen Video Hero",
      category: "Hero",
      provider: "custom",
      previewComponent: "VideoHeroDemo",
      sourceUrl: "#",
      tags: ["video", "autoplay", "interactive", "modern"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "hero-video-02",
      title: "Modern Video Hero",
      category: "Hero",
      provider: "custom",
      previewComponent: "ModernVideoHeroDemo",
      sourceUrl: "#",
      tags: ["video", "autoplay", "interactive", "modern"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "hero-video-03",
      title: "Rounded Bento Grid Video Hero",
      category: "Hero",
      provider: "custom",
      previewComponent: "RoundedBentoVideoHeroDemo",
      sourceUrl: "#",
      tags: ["video", "autoplay", "interactive", "modern"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "carousel-logo-video-01",
      title: "Logo Carousel",
      category: "Carousel",
      provider: "custom",
      previewComponent: "LogoCarouselVideoHeroDemo",
      sourceUrl: "#",
      tags: ["video", "autoplay", "interactive", "modern", "carousel"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "button-subscribe-01",
      title: "Subscribe Button",
      category: "Buttons",
      provider: "custom",
      previewComponent: "SubscribeButtonDemo",
      sourceUrl: "#",
      tags: ["animated", "hover", "modern", "interactive"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "button-explore-01",
      title: "Explore Button",
      category: "Buttons",
      provider: "custom",
      previewComponent: "ExploreButtonDemo",
      sourceUrl: "#",
      tags: ["animated", "hover", "modern", "interactive", "icon"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "button-learn-more-01",
      title: "Learn More Button",
      category: "Buttons",
      provider: "custom",
      previewComponent: "LearnMoreButtonDemo",
      sourceUrl: "#",
      tags: ["animated", "hover", "modern", "interactive", "icon"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "button-interactive-hover-01",
      title: "Interactive Hover Button",
      category: "Buttons",
      provider: "custom",
      previewComponent: "InteractiveHoverButtonDemo",
      sourceUrl: "#",
      tags: ["animated", "hover", "modern", "interactive", "icon"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "button-ripple-01",
      title: "Ripple Button",
      category: "Buttons",
      provider: "custom",
      previewComponent: "RippleButtonDemo",
      sourceUrl: "#",
      tags: ["animated", "ripple", "modern", "interactive"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "button-shiny-01",
      title: "Shiny Button",
      category: "Buttons",
      provider: "custom",
      previewComponent: "ShinyTextDemo",
      sourceUrl: "#",
      tags: ["animated", "shiny", "modern", "text-effect"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "button-subscribe-v2-01",
      title: "Subscribe Button V2",
      category: "Buttons",
      provider: "custom",
      previewComponent: "SubscribeButtonV2Demo",
      sourceUrl: "#",
      tags: ["animated", "hover", "modern", "interactive", "icon"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "button-neumorphic-01",
      title: "Neumorphic Button",
      category: "Buttons",
      provider: "custom",
      previewComponent: "NeumorphicButtonDemo",
      sourceUrl: "#",
      tags: ["neumorphic", "modern", "interactive", "pressed-effect"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "carousel-feature-steps-01",
      title: "Feature Steps Carousel",
      category: "Carousel",
      provider: "custom",
      previewComponent: "FeatureStepsDemo",
      sourceUrl: "#",
      tags: ["animated", "carousel", "modern", "interactive", "autoplay"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "carousel-circular-testimonials-01",
      title: "Circular Testimonials Carousel",
      category: "Carousel",
      provider: "custom",
      previewComponent: "CircularTestimonialsDemo",
      sourceUrl: "#",
      tags: ["animated", "carousel", "modern", "interactive", "autoplay", "testimonials"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "carousel-circular-gallery-01",
      title: "Circular Gallery",
      category: "Carousel",
      provider: "custom",
      previewComponent: "CircularGalleryDemo",
      sourceUrl: "#",
      tags: ["animated", "carousel", "modern", "interactive", "3d", "gallery"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "carousel-portfolio-01",
      title: "Progress Bar Carousel",
      category: "Carousel",
      provider: "custom",
      previewComponent: "PortfolioCarouselDemo",
      sourceUrl: "#",
      tags: ["animated", "carousel", "modern", "interactive", "portfolio", "autoplay"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "carousel-testimonial-slider-video-01",
      title: "Testimonial Slider",
      category: "Carousel",
      provider: "custom",
      previewComponent: "TestimonialSliderVideoHeroDemo",
      sourceUrl: "#",
      tags: ["video", "autoplay", "interactive", "modern", "testimonials", "carousel"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "carousel-stagger-testimonials-01",
      title: "Stagger Testimonials",
      category: "Carousel",
      provider: "custom",
      previewComponent: "StaggerTestimonialsDemo",
      sourceUrl: "#",
      tags: ["animated", "carousel", "modern", "interactive", "testimonials", "stagger"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "split-text-animation",
      title: "Split Text Animation",
      category: "Text Animations",
      provider: "reactbits.dev",
      previewComponent: "SplitTextDemo",
      sourceUrl: "https://www.reactbits.dev/components/split-text",
      tags: ["text", "animation", "scroll", "gsap", "split"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "blur-text-animation",
      title: "Blur Text Reveal",
      category: "Text Animations",
      provider: "custom",
      previewComponent: "BlurTextDemo",
      sourceUrl: "https://motion.dev/",
      tags: ["text", "animation", "intersection", "blur", "motion"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "circular-text-animation",
      title: "Circular Text Spinner",
      category: "Text Animations",
      provider: "custom",
      previewComponent: "CircularTextDemo",
      sourceUrl: "#",
      tags: ["text", "animation", "circular", "rotation", "motion"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "text-type-animation",
      title: "Typed Text Animator",
      category: "Text Animations",
      provider: "custom",
      previewComponent: "TextTypeDemo",
      sourceUrl: "#",
      tags: ["text", "animation", "typing", "cursor", "loop"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "scroll-reveal-animation",
      title: "Scroll Reveal Text",
      category: "Text Animations",
      provider: "custom",
      previewComponent: "ScrollRevealDemo",
      sourceUrl: "#",
      tags: ["text", "animation", "scroll", "reveal", "blur", "gsap"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "scroll-float-animation",
      title: "Scroll Float Text",
      category: "Text Animations",
      provider: "custom",
      previewComponent: "ScrollFloatDemo",
      sourceUrl: "#",
      tags: ["text", "animation", "scroll", "float", "bounce", "gsap"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "color-palette-analogous-sunrise",
      title: "Analogous Sunrise Palette",
      category: "Color Palettes",
      provider: "custom",
      previewComponent: "ColorPalettesDemo",
      sourceUrl: "#",
      tags: ["colors", "palette", "analogous", "sunrise", "warm", "black", "design"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "color-palette-analogous-citrus",
      title: "Analogous Citrus Palette",
      category: "Color Palettes",
      provider: "custom",
      previewComponent: "ColorPalettesDemo",
      sourceUrl: "#",
      tags: ["colors", "palette", "analogous", "citrus", "bright", "black", "design"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "color-palette-analogous-ember",
      title: "Analogous Ember Palette",
      category: "Color Palettes",
      provider: "custom",
      previewComponent: "ColorPalettesDemo",
      sourceUrl: "#",
      tags: ["colors", "palette", "analogous", "ember", "warm", "black", "design"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "color-palette-mono-amber",
      title: "Monochrome Amber Palette",
      category: "Color Palettes",
      provider: "custom",
      previewComponent: "ColorPalettesDemo",
      sourceUrl: "#",
      tags: ["colors", "palette", "monochrome", "amber", "warm", "black", "design"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "color-palette-mono-glow",
      title: "Monochrome Glow Palette",
      category: "Color Palettes",
      provider: "custom",
      previewComponent: "ColorPalettesDemo",
      sourceUrl: "#",
      tags: ["colors", "palette", "monochrome", "glow", "soft", "black", "design"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
    {
      id: "color-palette-mono-deep",
      title: "Monochrome Deep Palette",
      category: "Color Palettes",
      provider: "custom",
      previewComponent: "ColorPalettesDemo",
      sourceUrl: "#",
      tags: ["colors", "palette", "monochrome", "deep", "rich", "black", "design"],
      license: "MIT",
      version: "1.0.0",
      badges: ["new"],
    },
  ],
  guidance: [
    {
      category: "Navigation Menu",
      guidance:
        "The Navigation Menu is the primary navigation bar at the top of your website. It helps visitors find and access different pages and sections. Look for navigation clarity, logo prominence, how it behaves on scroll, and behaviour on hover.",
      estTimeMins: 2,
    },
    {
      category: "Hero",
      guidance:
        "The Hero section is the first large, prominent area visitors see when they land on your website. It typically includes a headline, supporting text, and a primary call-to-action button. Focus on headline impact, supporting text, and primary call-to-action alignment.",
      estTimeMins: 3,
    },
    {
      category: "Buttons",
      guidance:
        "Buttons are interactive elements that trigger actions when clicked. They guide users through your website and encourage conversions. Consider size, contrast, hover/focus states, and how primary vs. secondary differ.",
      estTimeMins: 2,
    },
    {
      category: "Carousel",
      guidance:
        "A Carousel is a rotating display of content, images, or cards that automatically cycles through items. It's used to showcase multiple pieces of content in a limited space. Consider navigation controls, transition smoothness, autoplay behavior, and mobile responsiveness.",
      estTimeMins: 3,
    },
    {
      category: "Text Animations",
      guidance:
        "Text Animations add visual interest and emphasis to headings, paragraphs, or key messages. They can reveal content on scroll, split and animate letters, or create eye-catching effects. Consider animation timing, readability, performance impact, and how the animation enhances (not distracts from) your message.",
      estTimeMins: 2,
    },
    {
      category: "Color Palettes",
      guidance:
        "Color palettes define the visual personality of your website. Each palette includes a fixed brand orange (#f68634) with complementary colors for backgrounds, text, buttons, and accents. Consider how colors work together, accessibility contrast ratios, and how they align with your brand identity and target audience.",
      estTimeMins: 3,
    },
  ],
};


